export const userTypes = {
    USERS_SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
    USERS_SIGNUP_ERROR: 'USERS_SIGNUP_ERROR',

    GET_INFO: 'GET_INFO',
    GET_USERS: 'GET_USERS',
    GET_USER_CHALLENGES: 'GET_USER_CHALLENGES',
    USERS_LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    USERS_LOGIN_ERROR: 'USERS_LOGIN_ERROR',

    USERS_LOGOUT: 'USERS_LOGOUT'
};
export const challengeTypes = {
    FIND_CHALLENGES: 'FIND_CHALLENGES',
    ENTER_CODE: 'ENTER_CODE'
};